mybatis:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.zhya.workformenovel.entity
  configuration:
    cache-enabled: true
spring:
  datasource:
    url: jdbc:mysql://47.101.152.104:3306/eureka?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    druid:
      username: root
      password: zhouyaok66810743
      max-wait: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    port: 5672
    username: admin
    password: zhouyaok123
    host: 47.101.152.104
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      uri: mongodb://root:zhouyaok@47.101.152.104:27017
      database: novelContent

logging:
  level:
    com.zhya.workformenovel.dao: error

eureka:
  client:
    service-url:
      defaultZone: http://47.101.152.104:8050/eureka/
    #允许使用eureka
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: workformenovel
    hostname: localhost
